global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo:8080']
        labels:
          instance: demo



